/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uI.desktop;

import javax.swing.JOptionPane;

/**
 *
 * @author formando
 */
public class FrmStarted extends javax.swing.JFrame {

    /**
     * Creates new form FrmStarted
     */
    public FrmStarted() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtDados = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFicheiro = new javax.swing.JMenu();
        mnuFicheiroAbrir = new javax.swing.JMenuItem();
        mnuSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuGestaoRH = new javax.swing.JMenu();
        mnuNovaPessoa = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtDados.setColumns(20);
        txtDados.setRows(5);
        jScrollPane1.setViewportView(txtDados);

        mnuFicheiro.setText("Ficheiro");

        mnuFicheiroAbrir.setText("Abrir");
        mnuFicheiro.add(mnuFicheiroAbrir);

        mnuSair.setText("Sair");
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        mnuFicheiro.add(mnuSair);

        jMenuBar1.add(mnuFicheiro);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        mnuGestaoRH.setText("GestaoRH");

        mnuNovaPessoa.setText("Nova Pessoa");
        mnuNovaPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNovaPessoaActionPerformed(evt);
            }
        });
        mnuGestaoRH.add(mnuNovaPessoa);

        jMenuBar1.add(mnuGestaoRH);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        sairPrograma();
    }//GEN-LAST:event_mnuSairActionPerformed

    private void mnuNovaPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNovaPessoaActionPerformed
        JDialogEditarPessoa jDeditarPessoa = new JDialogEditarPessoa(this, true);
        jDeditarPessoa.setVisible(true);
        System.out.println(jDeditarPessoa.getBtnPressionado());
        txtDados.setText(txtDados.getText()+"\n"+jDeditarPessoa.getPessoa().toString());
       
    }//GEN-LAST:event_mnuNovaPessoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmStarted.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmStarted.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmStarted.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmStarted.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmStarted().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu mnuFicheiro;
    private javax.swing.JMenuItem mnuFicheiroAbrir;
    private javax.swing.JMenu mnuGestaoRH;
    private javax.swing.JMenuItem mnuNovaPessoa;
    private javax.swing.JMenuItem mnuSair;
    private javax.swing.JTextArea txtDados;
    // End of variables declaration//GEN-END:variables

    private void sairPrograma(){
        if (JOptionPane.showConfirmDialog(rootPane, "Quer mesmo sair?", "Sair", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)==JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }
            
}
